apiVersion: v1
kind: Secret
metadata:
  name: langfuse-secrets
  namespace: genai-platform
type: Opaque
data:
  # These are base64 encoded placeholders
  NEXTAUTH_SECRET: eW91cnNlY3JldA== # "yoursecret"
  SALT: eW91cnNhbHQ= # "yoursalt"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: langfuse-db
  namespace: genai-platform
spec:
  serviceName: "langfuse-db"
  replicas: 1
  selector:
    matchLabels:
      app: langfuse-db
  template:
    metadata:
      labels:
        app: langfuse-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        volumeMounts:
        - name: langfuse-db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: langfuse-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: langfuse-db
  namespace: genai-platform
spec:
  selector:
    app: langfuse-db
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse
  namespace: genai-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse
  template:
    metadata:
      labels:
        app: langfuse
    spec:
      containers:
      - name: langfuse
        image: langfuse/langfuse:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@langfuse-db:5432/postgres"
        - name: NEXTAUTH_URL
          value: "http://langfuse.local"
        - name: LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES
          value: "true"
        envFrom:
        - secretRef:
            name: langfuse-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: langfuse
  namespace: genai-platform
spec:
  selector:
    app: langfuse
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langfuse-ingress
  namespace: genai-platform
spec:
  rules:
  - host: langfuse.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: langfuse
            port:
              number: 80