apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: genai-platform
  namespace: flux-system
spec:
  interval: 1m
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: genai-platform
  targetNamespace: genai-platform