apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: genai-platform
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/yourusername/genai-platform
  ref:
    branch: main